### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jeffmackinnon** [pelican-plugins/fediverse#1]
This is exactly something that I have been looking for.

There are a couple of features that I would love to see in future releases (and if I find time to hack-away I will add a pull-request), they are:

- prevent unlisted posts from the list (maybe its there)
- Prevent categories (or whitelist categories)
- select post type to mastodon: public, unlisted, local
- upload an image with the post, if an image isn't available include a "default" - I use pelican-photos and it could be that, or it could be the social graph image (probably harder)
- Use API keys vs username/psw in the config file. 
- Update readme for install instructions.

When I get some testing/playing time I will try to knock a couple off this list.

**Comment by mpaglia0** [comment]
Ciao @Jeffmackinnon!
Thank you for your request.
Pls note I am not a Python developer. Mastodon-toot has been written for my personal needs and now I have the right tool for my website.
I wrote it lurking around and with many copy/paste from other plugins.
Nevertheless I think your suggestions are interesting.
I will try to do something.
Thanks!

**Comment by Jeffmackinnon** [comment]
Awesome! I'm not a developer either, but maybe we can duct tape something together. 

I haven't performed a pull-request before, but I should have some time in a couple weeks to put something together for my site and will send a pull-request with the changes. 

Cheers,
JM

**Comment by silverhook** [comment]
Another not-delevoper here, but happy to help.

@Jeffmackinnon , perhaps it would be more manageable if you divide your feature request list into a issue each and we can tackle each one separately?

**Comment by mpaglia0** [comment]
Hi guys,
today I planned with Justin Mayer to move Pelica-toot in the official Pelican plugins repo!
The plugin will be renamed in `pelican-fediverse` with the aim to became a universal plugin for all the Fediverse and not only for Mastodon.
So, please, be patient untill the plugin will be moved in its final position.
Thank you!

**Comment by Jeffmackinnon** [comment]
@mpaglia0 has there been any update/changes to this process?

**Comment by mpaglia0** [comment]
Ciao, the plugin is not yet included in the official repo.
Nevertheless I think you can start to contribute anyway, if you desire.
Thanks

**Comment by mpaglia0** [comment]
Pelican-fediverse is now available from the main pelican plugin repo!
